### ISSUE TITLE
[BE] TicketEntryTime의 검증 로직을 Ticket의 addTicketEntryTime 메소드로 이동한다.

### ISSUE THREAD

**Issue by seokjin8678** [woowacourse-teams/2023-festa-go#155]
## ✨ 세부 내용

TicketEntryTime의 검증 로직을 Ticket의 addTicketEntryTime 메소드로 이동합니다.

이유는 다음과 같습니다.

1. TicketEntryTime은 엔티티지만, 필드에는 참조하는 다른 엔티티가 없는 값 객체에 가까움.
2. 해당 객체가 Stage의 의존성과 Stage의 시작 시간에 관한 정보를 알 필요는 없음
3. TicketEntryTime 엔티티의 영속은 Ticket의 addTicketEntryTime 메서드에서 영속
4. 따라서 생성 시 로직을 addTicketEntryTime 메서드에서 하는게 좋아보임

## ⏰ 예상 소요 시간

30분

**Comment by seokjin8678** [comment]
리팩터링한 커밋은 다음과 같습니다.
8d9eb4ac940097d219cc11f5b4539690db658e8d

**Comment by carsago** [comment]
저도 이런 방식으로 푸는게 더 좋아보입니다.
TicketEntryTime의 제약조건이 ```TicketEntriyTime.of()```라는 정적팩토리 메소드에만 의존해서 검증되는 것도 부담스럽고요.

**Comment by xxeol2** [comment]
값객체라 샹각하니까 이 방식이 더 자연스러워보이네요!

**Comment by BGuga** [comment]
2번 이유가 상당히 납득이 되네요!
