### ISSUE TITLE
[BUG] 방문객, 재학생을 선택하지 않아도 예매하기 버튼이 활성화되어 있어요

### ISSUE THREAD

**Issue by thdwoqor** [woowacourse-teams/2023-festa-go#254]
### 버그 사항
방문객, 재학생을 선택하지 않아도 예매하기 버튼이 활성화되어 있어요
 
### **Screenshots**
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/83541246/a840c08c-0518-4997-abb3-acf7a75f6fe4)
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/83541246/392093fb-1109-46ed-8702-ebc9394de9a4)

**Comment by SeongHoonC** [comment]
반영했습니다! 버그 리포팅 감사합니다!
