### ISSUE TITLE
[BUG] 예매 반복 가능 버그

### ISSUE THREAD

**Issue by kong-hana01** [woowacourse-teams/2023-festa-go#255]
### 버그 사항

- 동일한 축제에 대한 티켓을 계속 예매해도 예매가 됩니다~~

### 버그 simulation

- 1. 로그인하지 않은 유저가 한 축제에서 티켓을 예매한다.
- 2. 발급받은 티켓을 확인한 이후에 다시 한번 더 해당 축제의 동일한 티켓을 예매한다.
- 3. 위의 과정을 반복할 수 있다.

### 원하던 상황

- 한 사용자에 대해서는 하나의 티켓 예매만 가능하도록 수정하면 좋을 것 같습니다 ㅎㅎ

### **Screenshots**
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/79015120/04845e46-d43a-49ac-8566-2712ff842f69)
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/79015120/78c8fc38-ffa6-428d-a4af-d594234246b9)
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/79015120/bef5f358-b233-42f6-a613-f1ddd257f452)

**Comment by seokjin8678** [comment]
#288
