### ISSUE TITLE
[BUG] 축제날짜가 지난 티켓이 예매가 된다.

### ISSUE THREAD

**Issue by Choisehyeon** [woowacourse-teams/2023-festa-go#256]
### 버그 사항
테코 대학교 축제가 일정이 지났는데 사라지지 않고 노출되며 이를 예매하려고 하면 예매가 된다.

 

### 버그 simulation
테코대학교 축제가 일정이 지났는데 노출되어 있었고
들어가서 예매를 해보니 예매가 되는 상황

### 원하던 상황
일정이 지나면 축제가 노출이 안되면 좋을 것 같아요!!
일정이 지난 축제에 예매 요청이 오면 백엔드도 검증을 하면 좋을 것 같습니다!

### **Screenshots**
![Screenshot_20230807-142325_festago](https://github.com/woowacourse-teams/2023-festa-go/assets/50761690/0ab54834-9ccf-4903-8c15-984c683063d1)
![Screenshot_20230807-142322_festago](https://github.com/woowacourse-teams/2023-festa-go/assets/50761690/3542259d-0979-4cd6-b01f-1fc0be0f6581)
![Screenshot_20230807-142313_festago](https://github.com/woowacourse-teams/2023-festa-go/assets/50761690/637c21bf-5d0f-4fc8-be2f-4f147919a66c)

**Comment by xxeol2** [comment]
#289
