### ISSUE TITLE
[AN] 로그인 화면에서 뒤로가기 버그 수정

### ISSUE THREAD

**Issue by re4rk** [woowacourse-teams/2023-festa-go#340]
## ✨ 세부 내용

- 로그인 화면에서 뒤로가기시 바텀네비게이션이 바뀌지 않는 버그 수정

## ⏰ 예상 소요 시간

- 5시간
<img width="298" alt="스크린샷 2023-08-11 오후 5 10 03" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/6e4be7ed-630c-4b08-9b07-dab4544b4e09">

**Comment by SeongHoonC** [comment]
다른 이슈에서 적용 완료했습니다!
