### ISSUE TITLE
[BE] 에러 로그 형식을 Level에 따라 구분하고, Id와 Role을 남긴다.

### ISSUE THREAD

**Issue by seokjin8678** [woowacourse-teams/2023-festa-go#396]
## ✨ 세부 내용

로그의 형식이 Info, Warn, Error 구분 없이 다음과 같이 로그가 기록됩니다.
```
[🚨ERROR] - (POST /admin/warn)
FOR_TEST_ERROR
com.festago.exception.InternalServerException: 테스트용 에러입니다.
```

따라서 다음과 같이 레벨 별로 로그를 분리하는게 가독성 측면에서 좋을 것 같습니다.
또한 로그에 id와 role을 추가하여, 어떤 사용자로 부터 에러가 발생했는지 추적하는게 좋을지 싶습니다.
```
[🔵INFO] - (POST /admin/info)
(id: 1, role: MEMBER)
FOR_TEST_ERROR
 com.festago.exception.BadRequestException: 테스트용 에러입니다.
 
[🟠WARN] - (POST /admin/warn)
(id: 1, role: MEMBER)
FOR_TEST_ERROR
 com.festago.exception.InternalServerException: 테스트용 에러입니다.
  at com.festago.presentation.AdminController.getWarn(AdminController.java:134)

[🔴ERROR] - (POST /admin/error)
(id: 1, role: MEMBER)
 java.lang.IllegalArgumentException: 테스트용 에러입니다.
  at com.festago.presentation.AdminController.getError(AdminController.java:129)
```

또한 INFO 로그의 경우, 사용자가 잘못된 값을 입력했을 때 발생하는 오류이므로, Exception을 넘겨 스택 트레이스까지 출력할 필요는 없다고 생각합니다.
따라서 단순히 Exception Class와 Message만 출력하는게 좋을 것 같습니다.
(티켓이 매진됐을 때 BadRequestException이 많이 발생할텐데, 이때도 스택 트레이스를 출력한다면 많은 과부하가 발생할듯)
이에 대해 생각이 다를 수 있으므로 해당 부분은 논의가 필요할 것 같습니다.

## ⏰ 예상 소요 시간

2시간

**Comment by BGuga** [comment]
> 따라서 다음과 같이 레벨 별로 로그를 분리하는게 가독성 측면에서 좋을 것 같습니다.

에러 패키지기 분리되어 있을 때는 분리할 필요성을 크게 못느꼈는데 prod 에서 warn 과 error 구분에 어려움이 생기고 있던 것 같네요 ㅎㅎ. 동의합니다.

> 또한 INFO 로그의 경우, 사용자가 잘못된 값을 입력했을 때 발생하는 오류이므로, Exception을 넘겨 스택 트레이스까지 출력할 필요는 없다고 생각합니다.
따라서 단순히 Exception Class와 Message만 출력하는게 좋을 것 같습니다.
(티켓이 매진됐을 때 BadRequestException이 많이 발생할텐데, 이때도 스택 트레이스를 출력한다면 많은 과부하가 발생할듯)

info log 의 경우에 기존에도 stack trace 를 남기지 않도록 하였는데 log, logWithTrace 메서드들을 삭제하고 대체하는 과정에서 잘못 들어간 것 같네요 삭제해아 할 것 같습니다

> 또한 로그에 id와 role을 추가하여, 어떤 사용자로 부터 에러가 발생했는지 추적하는게 좋을지 싶습니다.

어떤 유저가 에러를 발생시키고 있는지 추적하기 위한 로그 정보를 추가하는 것 너무 좋습니다 👍. 
여기서 문득 사용자의 요청이 에러를 발생시켰을 떄만 로깅을 해야하는가 의문이 드네요.
예를 들어 DB 를 여러번 요청하는 다소 무거운 method A 를 반복적으로 호출하여 서버에 트래픽을 건다면 해당 유저가 누군지 식별해내야할 필요가 있을 것 같습니다. 하지만 해당 요청 자체가 에러는 아닙니다.
이런 것까지 고려한다면 모든 요청을 로깅해야 하는 것인가라는 의문이 드네요...

**Comment by xxeol2** [comment]
> 예를 들어 DB 를 여러번 요청하는 다소 무거운 method A 를 반복적으로 호출하여 서버에 트래픽을 건다면 해당 유저가 누군지 식별해내야할 필요가 있을 것 같습니다. 하지만 해당 요청 자체가 에러는 아닙니다.
> 이런 것까지 고려한다면 모든 요청을 로깅해야 하는 것인가라는 의문이 드네요...

동의합니다.. 그런데 POST요청이 많지 않은 서비스 특성상 지금 당장은 모든 요청을 로깅하는게 더 부담일 것 같아요.
에러가 아닌 요청을 로깅하자면... 티켓 예매정도 로깅하면 좋을 것 같네요!

**Comment by xxeol2** [comment]
아주 좋습니다 👍 token이 없는 요청인 경우엔 (id: 1, role: MEMBER) 부분을 생략하면 좋을 것 같네요!

**Comment by seokjin8678** [comment]
> > 따라서 다음과 같이 레벨 별로 로그를 분리하는게 가독성 측면에서 좋을 것 같습니다.
> 
> 에러 패키지기 분리되어 있을 는 분리할 필요성을 크게 못느꼈는데 prod 에서 warn 과 error 구분에 어려움이 생기고 있던 것 같네요 ㅎㅎ. 동의합니다.
> 
> > 또한 INFO 로그의 경우, 사용자가 잘못된 값을 입력했을 때 발생하는 오류이므로, Exception을 넘겨 스택 트레이스까지 출력할 필요는 없다고 생각합니다.
> > 따라서 단순히 Exception Class와 Message만 출력하는게 좋을 것 같습니다.
> > (티켓이 매진됐을 때 BadRequestException이 많이 발생할텐데, 이때도 스택 트레이스를 출력한다면 많은 과부하가 발생할듯)
> 
> info log 의 경우에 기존에도 stack trace 를 남기지 않도록 하였는데 log, logWithTrace 메서드들을 삭제하고 대체하는 과정에서 잘못 들어간 것 같네요 삭제해아 할 것 같습니다
> 
> > 또한 로그에 id와 role을 추가하여, 어떤 사용자로 부터 에러가 발생했는지 추적하는게 좋을지 싶습니다.
> 
> 어떤 유저가 에러를 발생시키고 있는지 추적하기 위한 로그 정보를 추가하는 것 너무 좋습니다 👍. 여기서 문득 사용자의 요청이 에러를 발생시켰을 때만 로깅을 해야하는가 의문이 드네요. 예를 들어 DB 를 여러번 요청하는 다소 무거운 method A 를 반복적으로 호출하여 서버에 트래픽을 건다면 해당 유저가 누군지 식별해내야할 필요가 있을 것 같습니다. 하지만 해당 요청 자체가 에러는 아닙니다. 이런 것까지 고려한다면 모든 요청을 로깅해야 하는 것인가라는 의문이 드네요...

필터 혹은 AOP로 1분에 일정 이상의 요청을 보내는 사용자는 잠깐 블럭 처리를 한다거나 방법이 있을 것 같네요!

**Comment by carsago** [comment]
너무 늦게봤네요 ㅠㅠ 굳이 필요하지 않으니 Info의 stackTrace는 삭제하는게 좋겠네요. 어차피 ErrorMessage로 어디서 발생하는지 확인가능하니까요.
