### ISSUE TITLE
[BE] TestFixture의 메소드 네이밍 컨벤션을 변경한다.

### ISSUE THREAD

**Issue by carsago** [woowacourse-teams/2023-festa-go#414]
## ✨ 세부 내용

현재 테스트 픽스쳐를 생성할 때 메소드 네이밍 컨벤션을 다음과 같이 변경할 예정입니다.

```
// Before
StageFixture.stage() <----
.festival(festival)
...
.build();

// After
StageFixture.builder() <----
.festival(festival)
...
.build();
```

기대효과
1. builder()로 생성하는 것이 보편적인 컨벤션이라 이해하기 쉬움.
2. 여러개의 domain을 chaining할 때 가독성이 개선됨.

주의 
- 변경사항이 테스트 코드 전반적으로 작용함으로 conflict 조심하고 진행

## ⏰ 예상 소요 시간

1 시간

**Comment by seokjin8678** [comment]
반영되었으므로, close 처리합니다!
