### ISSUE TITLE
[BE]  Redis 를 이용해서 티켓 예매를 진행한다.

### ISSUE THREAD

**Issue by BGuga** [woowacourse-teams/2023-festa-go#427]
## ✨ 세부 내용

예매시간 1시간까지는 Redis 에 티켓 정보를 저장해두어서 해당 데이터를 기반으로 예매한다.

## ⏰ 예상 소요 시간

4시간

**Comment by xxeol2** [comment]
Redis 기술검토 이슈로 #425 이슈로 통합.
