### ISSUE TITLE
[BE] 학생 인증 코드가 유효하지 않을 시 500이 아닌 400 에러를 반환한다.

### ISSUE THREAD

**Issue by xxeol2** [woowacourse-teams/2023-festa-go#447]
## ✨ 세부 내용

현재 학생인증 코드가 숫자가 아니거나, 6자리가 아니면 500 에러가 발생합니다.
<img width="704" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/71129059/104a3257-6878-437b-bd46-a7427ac68132">
하지만 이는 사용자가 코드를 잘못 입력한것으로, 500에러가 아닌 400에러가 나는 것이 더 적절하다 생각하는데 어떻게 생각하시나요!

## ⏰ 예상 소요 시간

30분

**Comment by seokjin8678** [comment]
도메인 계층의 입력 값에 대한 검증은 `InternalServer`를 던지고, 프레젠테이션 계층의 입력 값에 대한 검증은 `BadRequest` 예외를 던지게 하는 것은 어떤가요?

**Comment by xxeol2** [comment]
- #482
