### ISSUE TITLE
[BE] Repository에서 Optional로 반환하는 메서드를 개선한다.

### ISSUE THREAD

**Issue by seokjin8678** [woowacourse-teams/2023-festa-go#594]
## ✨ 세부 내용

대부분의 로직에서 `Repository`로 엔티티를 찾는 메서드에 `orElseThrow` 메서드를 사용하고 있습니다.
하지만 공용으로 자주 쓰이는 `Repository`에서(MemberRepository) 해당 로직이 중복되는 경우가 많기 때문에 `default` 메서드를 사용하여 중복을 개선합니다.

```java
public interface MemberRepository extends JpaRepository<Member, Long> {

    default Member getOrThrow(Long id) {
        return findById(id)
            .orElseThrow(() -> new NotFoundException(ErrorCode.MEMBER_NOT_FOUND));
    }
}
``` 

이때 해당 메서드의 네이밍을 무엇을 하는게 좋을지 논의가 필요합니다.

## ⏰ 예상 소요 시간

1시간

**Comment by carsago** [comment]
getByID는 어떤가요? 전부 다 한번에 바꿀 수도 있고 하나씩 바꾸어가는 것도 좋을 것 같네요.

**Comment by seokjin8678** [comment]
> getByID는 어떤가요? 전부 다 한번에 바꿀 수도 있고 하나씩 바꾸어가는 것도 좋을 것 같네요.

`getById`라는 메서드는 이미 `JpaRepository`에 구현 메소드로 정의가 되어 있더군요.
게다가 `@Deprecated` 처리까지 된 상태라서리...

그리고 밑의 링크는 제이슨이 올리신 이슈 내용입니다.
https://github.com/woowacourse/service-apply/issues/565#issuecomment-1704300145
결론으로 `getOrThrow` 라는 네이밍을 사용하는 것 같네요.

저희 프로젝트에서 코틀린을 사용하지 않으니, `get` 이라는 메서드 이름을 사용해도 괜찮을 것 같긴 한데...
명시적으로 하려면 `getOrThrow`가 명확한 것 같네요.

**Comment by carsago** [comment]
getOrThrow가 더 명시적이네요. 어떠한 명칭이든 우리가 이해하기만 하면 괜찮다고 생각합니다.

**Comment by seokjin8678** [comment]
close #648
