### ISSUE TITLE
[BE] 학교 정보 API에 Swagger Annotation을 추가한다.

### ISSUE THREAD

**Issue by carsago** [woowacourse-teams/2023-festa-go#597]
## ✨ 세부 내용

설명이 없는 School Api에 Swagger Annotation을 작성해줍니다.

<img width="1433" alt="스크린샷 2023-11-03 오후 2 43 07" src="https://github.com/woowacourse-teams/2023-festa-go/assets/100915276/088f6283-5017-48df-9d91-3b4b7984682e">

## ⏰ 예상 소요 시간

20분

**Comment by seokjin8678** [comment]
Duplicate of #581

**Comment by carsago** [comment]
> Duplicate of #581

헐
