### ISSUE TITLE
[BE] 축제 목록 조회를 위한 API 생성

### ISSUE THREAD

**Issue by BGuga** [woowacourse-teams/2023-festa-go#657]
## ✨ 세부 내용

다음 두 개의 API를 생성합니다

인기 축제 목록 조회
`/api/v1/popular/festivals`

축제 목록 조회
`/api/v1/festivals`

## ⏰ 예상 소요 시간

8시간

---

글렌
- [ ] #658

**Comment by seokjin8678** [comment]
- [ ] 학교 CRUD 기능을 새롭게 추가한다.
